# --- RabbitMQ connection ---
rabbitmq.host=localhost
rabbitmq.port=5672
rabbitmq.username=guest
rabbitmq.password=guest


rabbitmq.queue=device.data.queue


# EUUID ul pentru device-ul meu
#il modific in functie de ce device vreau sa testez
#network router V5
simulator.device-id=6953eeab-8743-4b3d-a9d0-43cad51904b6

# Pentru test: 10000 (10 secunde) ca sa vezi repede rezultatele.
simulator.interval.millis=1000
