networks:
  proxy:
  backend:

volumes:
  user_db_data:
  device_db_data:
  auth_db_data: 

services:
  # ------------ Reverse proxy -------------
  traefik:
    image: traefik:v3.0
    container_name: traefik
    command:
      - --providers.docker=true
      - --providers.docker.exposedByDefault=false
      - --entrypoints.web.address=:80
    ports:
      - "80:80"     
    networks: [proxy]
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    depends_on: []
    

  # ------------ User DB -------------------
  user-db:
    image: postgres:16
    environment:
      POSTGRES_DB: users_db   
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
    volumes:
      - user_db_data:/var/lib/postgresql/data
    networks: [backend]
    ports:
      - "5433:5432"       
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user -d userdb"]
      interval: 5s
      timeout: 3s
      retries: 10

  # ------------ Device DB -----------------
  device-db:
    image: postgres:16
    environment:
      POSTGRES_DB: devices_db 
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
    volumes:
      - device_db_data:/var/lib/postgresql/data
    networks: [backend]
    ports:
      - "5434:5432"       
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U device -d devicedb"]
      interval: 5s
      timeout: 3s
      retries: 10

  #-------------------Auth DB--------------------
  auth-db:
    image: postgres:16
    environment:
      POSTGRES_DB: auth_db   
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
    volumes:
      - auth_db_data:/var/lib/postgresql/data
    networks: [backend]
    ports:
      - "5435:5432"       
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U auth -d authdb"]
      interval: 5s
      timeout: 3s
      retries: 10

  # ------------ User Service --------------
  user-service:
    build:
      context: ./user-service
      dockerfile: Dockerfile
    environment:
      SPRING_PROFILES_ACTIVE: docker
      USER_DB_HOST: user-db
      USER_DB_PORT: "5432"
      USER_DB_NAME: users_db
      USER_DB_USER: postgres
      USER_DB_PASS: root
      JWT_SECRET: VZk9R7q2eFj8Ls3pT4xN6wQy8Ua1BmCk5GhDfJ0Hs2Lp3Rv7Yq4Zd8Xe9TtVbWnC
      AUTH_SERVICE_BASE_URL: http://auth-service:8080
      INTERNAL_TOKEN: super-secret-sync
      SYNC_ENABLED: "false"
    depends_on:
      user-db:
        condition: service_healthy
    labels:
      - traefik.enable=true
      - traefik.http.routers.users.rule=PathPrefix(`/api/users`)
      - traefik.http.routers.users.entrypoints=web
      - traefik.http.services.users.loadbalancer.server.port=8080
    networks: [proxy, backend]

  # ------------ Device Service ------------
  device-service:
    build:
      context: ./device-service
      dockerfile: dockerfile   
    environment:
      SPRING_PROFILES_ACTIVE: docker
      DB_IP: device-db
      DB_PORT: 5432
      DB_DBNAME: devices_db     
      DB_USER: postgres
      DB_PASSWORD: root
      security.jwt.secret: VZk9R7q2eFj8Ls3pT4xN6wQy8Ua1BmCk5GhDfJ0Hs2Lp3Rv7Yq4Zd8Xe9TtVbWnC
    depends_on:
      device-db:
        condition: service_healthy
    labels:
      - traefik.enable=true
      - traefik.http.routers.devices.rule=PathPrefix(`/devices`)
      - traefik.http.routers.devices.entrypoints=web
      - traefik.http.services.devices.loadbalancer.server.port=8080
      - traefik.http.middlewares.devices-strip.stripprefix.prefixes=/devices
      - traefik.http.routers.devices.middlewares=devices-strip@docker
    networks: [proxy, backend]

 #-------------------------Auth service -------------------- 
  auth-service:
    build:
      context: ./auth-service
      dockerfile: Dockerfile
    environment:
      SPRING_PROFILES_ACTIVE: docker
      DB_HOST: auth-db
      DB_PORT: "5432"
      DB_NAME: auth_db
      DB_USER: postgres
      DB_PASS: root
      JWT_SECRET: VZk9R7q2eFj8Ls3pT4xN6wQy8Ua1BmCk5GhDfJ0Hs2Lp3Rv7Yq4Zd8Xe9TtVbWnC
      INTERNAL_TOKEN: super-secret-sync
      USER_SERVICE_BASE_URL: http://user-service:8080
      SYNC_ENABLED: "false"
    depends_on:
      auth-db:
        condition: service_healthy
    labels:
      - traefik.enable=true
      - traefik.http.routers.auth.rule=PathPrefix(`/api/auth`)
      - traefik.http.routers.auth.entrypoints=web
      - traefik.http.services.auth.loadbalancer.server.port=8080
    networks: [proxy, backend]

 # ------------ Frontend ------------------
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    depends_on:
      - user-service
      - device-service
      - auth-service
    labels:
      - traefik.enable=true
      - traefik.http.routers.web.rule=PathPrefix(`/`)
      - traefik.http.routers.web.entrypoints=web
      - traefik.http.services.web.loadbalancer.server.port=80
    networks: [proxy]