# Server
server.port=${PORT:8085}

spring.application.name=customer-support-service

# RabbitMQ (default local; in docker profile we'll point to rabbitmq)
spring.rabbitmq.host=${RABBIT_HOST:localhost}
spring.rabbitmq.port=${RABBIT_PORT:5672}
spring.rabbitmq.username=${RABBIT_USER:guest}
spring.rabbitmq.password=${RABBIT_PASS:guest}

# Chatbot queues
chat.request.queue=${CHAT_REQUEST_QUEUE:chat.request}
chat.response.queue=${CHAT_RESPONSE_QUEUE:chat.response}

# Security
security.jwt.secret=${JWT_SECRET:ds2025_super_secret_ds2025_super_secret}

# Swagger
springdoc.swagger-ui.path=/swagger-ui.html

# Helpful during dev
logging.level.org.springframework.amqp=INFO
logging.level.com.example.customersupport=INFO
